<?php
/**
 * Created by PhpStorm.
 * User: johann
 * Date: 28/02/18
 * Time: 11:35
 */

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use App\Entity\Sujet;
use App\Entity\Action;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\SubmitType;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

use Symfony\Component\Form\Extension\Core\Type\FileType;

use Symfony\Component\HttpFoundation\Request;




class ImportController extends Controller
{

  
    public function import(Request $request){

        $defaultData = array('message' => 'Type your message here');
        $form = $this->createFormBuilder($defaultData)
            ->add('Fichier', FileType::class ,array('label' => 'Fichier (CSV file)'))
            ->add('liste', ChoiceType::class, array(
            'choices' => array(
                'Action' => 'Action',
                'Sujet' => 'Sujet',
            ),))
            ->add('Send', SubmitType::class)
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // data is an array with "name", "email", and "message" keys
            $data = $form->getData();

            if ($data['Fichier']->getMimeType() != 'text/plain' ){

                throw $this->createNotFoundException(
                    'Erreur Format non pris en charge'
                );
            }


            $this->write_db(strtolower( $data['liste']),$this->open($data['Fichier']));

        }


        return $this->render('import.html.twig',array('form' => $form->createView()));
    }

    public function open($fichier){

//TODO Mettre le nom du fichier en paramétre de méthode

   $donnee = array();

        if (($handle = fopen($fichier, "r")) !== FALSE) {

            while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {

              array_push($donnee, $data);

            }
            fclose($handle);
        }else{
            throw $this->createNotFoundException(
                'Fichier pas trouvé'
            );
        }






        return $donnee;
        
    }


    public function write_db($nom_entité, $donnee){


        if ($nom_entité != 'sujet' AND $nom_entité != 'action'){

            throw $this->createNotFoundException(
                'Erreur entité inconnue'
            );
        }

        //Contruction Dynamiques
        $DynamicMethode = "set".$nom_entité;
        $nom_entité = "App\\Entity\\".(string)ucfirst($nom_entité);


        $em = $this->getDoctrine()->getManager();

        foreach ($donnee as $index => $item) {

            $entity = new $nom_entité;
            $entity->$DynamicMethode($item[0]);

            $em->persist($entity);
            $em->flush();

        }

    }

    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

}