#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
  path: /
  controller: App\Controller\GameController::home

app_explication:
  path: /explications
  controller: App\Controller\GameController::explications

app_regles:
  path: /regles
  controller: App\Controller\GameController::regles


app_game:
  path: /game/{id}
  controller: App\Controller\GameController::game
  defaults:
          id: 0
  requirements:
          id: '\d+'

app_list_game:
  path: /game/list
  controller: App\Controller\GameController::page_list_roleplay

app_add_scenar:
  path: /admin/add/scenar/{type}
  controller: App\Controller\AddscenarController::addscenar
  defaults:
          type: sujet



app_test:
  path: /import
  controller: App\Controller\ImportController::import


## Gestion des users
login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

sign:
  path: /creer-compte
  controller : App\Controller\SecurityController::sign